- name: Download Nomad Envoy
  get_url:
    url: "{{ nomad_envoy_tar_url }}"
    dest: "{{ role_path }}/files/{{ nomad_pkg }}"
    checksum: "sha256:{{ nomad_sha256.stdout }}"
    timeout: "42"
  become: false
  tags: installation
  delegate_to: 127.0.0.1
  when: not envoy_package.stat.exists

- name: Create Temporary Directory for Extraction
  tempfile:
    state: directory
    prefix: ansible-nomad-enovy.
  become: false
  register: install_temp
  tags: installation
  delegate_to: 127.0.0.1

- name: Unarchive Nomad-envoy
  unarchive:
    src: "{{ role_path }}/files/{{ nomad_pkg }}"
    dest: "{{ install_temp.path }}/"
    creates: "{{ install_temp.path }}/nomad"
  become: false
  tags: installation
  delegate_to: 127.0.0.1