---
# File: install.yml - package installation tasks for Nomad
- name: Make directory Nomad     
  file:
    path: "{{ item }}"  
    state: directory 
    owner: "root"
    group: "root"     
    mode: 0777   
  with_item:
    - "/etc/nomad"
       
- name: GET Nomad packages    
  get_url:
    url: "{{ nomad_archive_url }}"
    dest: /var/tmp
    mode: 0777
    checksum: sha256:b5bb9d8014a0f9b1d61e21e796d78eefdf1352f23cd32812f4850b878ae4944c

- name: Create Temporary Directory for Extraction
  tempfile:
    state: directory
    prefix: ansible-nomad.
  become: false
  register: install_temp
  tags: installation

- name: Unarchive Nomad
  unarchive:
    src: "{{ role_path }}/files/{{ nomad_pkg }}"
    dest: "{{ install_temp.path }}/"
    creates: "{{ install_temp.path }}/nomad"
  become: false
  tags: installation

- block:
    - name: systemd script
      template:
        src: "{{ nomad_systemd_template }}"
        dest: "{{ nomad_systemd_unit_path }}/nomad.service"
        owner: root
        group: root
        mode: 0644
      register: nomad_systemd_file
    - block:
      - name: reload systemd daemon
        systemd:
          daemon_reload: true
      - name: Enable nomad at startup (systemd)
        systemd:
          name: nomad
          enabled: yes
      when: nomad_systemd_file.changed
  when: ansible_service_mgr == "systemd"

- name: Start Nomad
  service:
    name: nomad
    enabled: true
    state: started
  when: not ansible_service_mgr == "systemd"


- name: Cleanup
  file:
    path: "{{ install_temp.path }}"
    state: "absent"
  become: false
  tags: installation
  

- name: Add Nomad group
  group:
    name: "{{ nomad_group }}"
    state: present
  when:
    - nomad_manage_group | bool

- name: Add Nomad user
  user:
    name: "{{ nomad_user }}"
    comment: "Nomad user"
    group: "{{ nomad_group }}"
    system: yes
  when:
    - nomad_manage_user | bool

- name: Install Nomad
  copy:
    src: "{{ install_temp.path }}/nomad"
    dest: "{{ nomad_bin_dir }}"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: 0755
