---
# File: main.yml - Main tasks for Nomad


- name: Install nomad packages
  include: install.yml

- name: Create directories
  file:
    dest: "{{ item }}"
    state: directory
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
  with_items:
    - "{{ nomad_data_dir }}"
    - "{{ nomad_plugin_dir }}"

- name: Base configuration
  template:
    src: base.hcl.j2
    dest: "{{ nomad_config_dir }}/base.hcl"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nomad

- name: Server configuration
  template:
    src: server.hcl.j2
    dest: "{{ nomad_config_dir }}/server.hcl"
    owner: root
    group: root
    mode: 0644
  when:
    - _nomad_node_server | bool
  notify:
    - restart nomad

- name: Client configuration
  template:
    src: client.hcl.j2
    dest: "{{ nomad_config_dir }}/client.hcl"
    owner: root
    group: root
    mode: 0644
  when:
    - _nomad_node_client | bool
  notify:
    - restart nomad

- name: Start Nomad
  service:
    name: nomad
    enabled: true
    state: started
  when: not ansible_service_mgr == "systemd"

- name: Install acl and voult
  include: config.yml

