---
# File: main.yml - Main tasks for Nomad

- name: Include checks/asserts
  include: asserts.yml

- name: Include OS variables
  include_vars: "{{ ansible_os_family }}.yml"

# Gathers facts (bind address) from servers not currently targeted.
# 'delegate_facts' is currently rather buggy in Ansible so this might not
# always work. Hence 'nomad_gather_server_facts' defaults to 'no'.
- name: Gather facts from other servers
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ nomad_servers | difference(play_hosts) }}"
  ignore_errors: true
  when: nomad_gather_server_facts | bool

- name: Expose bind_address, advertise_address and node_role as facts
  set_fact:
    nomad_bind_address: "{{ nomad_bind_address }}"
    nomad_advertise_address: "{{ nomad_advertise_address }}"
    nomad_node_role: "{{ nomad_node_role }}"

- name: Include user and group settings
  include: user_group.yml

- name: Include Docker tasks
  include: docker.yml
  when: nomad_docker_enable | bool

- name: Install OS packages
  include: install.yml

- name: Create directories
  file:
    dest: "{{ item }}"
    state: directory
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
  with_items:
    - "{{ nomad_data_dir }}"
    - "{{ nomad_plugin_dir }}"

- name: Install CNI plugin
  include: cni.yml
  when: nomad_cni_enable | bool #########

- name: Create config directory
  file:
    dest: "{{ nomad_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Base configuration
  template:
    src: base.hcl.j2
    dest: "{{ nomad_config_dir }}/base.hcl"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nomad

- name: Create TLS configuration
  include_tasks: tls.yml
  when: nomad_tls_enable | bool

- name: Server configuration
  template:
    src: server.hcl.j2
    dest: "{{ nomad_config_dir }}/server.hcl"
    owner: root
    group: root
    mode: 0644
  when:
    - _nomad_node_server | bool
  notify:
    - restart nomad

- name: Remove Server configuration
  file:
    dest: "{{ nomad_config_dir }}/server.hcl"
    state: absent
  when:
    - nomad_allow_purge_config | bool
    - not _nomad_node_server | bool
  notify:
    - restart nomad

- name: Client configuration
  template:
    src: client.hcl.j2
    dest: "{{ nomad_config_dir }}/client.hcl"
    owner: root
    group: root
    mode: 0644
  when:
    - _nomad_node_client | bool
  notify:
    - restart nomad

- name: Remove Client configuration
  file:
    dest: "{{ nomad_config_dir }}/client.hcl"
    state: absent
  when:
    - nomad_allow_purge_config | bool
    - not _nomad_node_client | bool
  notify:
    - restart nomad

- name: Start Nomad
  service:
    name: nomad
    enabled: true
    state: started
  when: not ansible_service_mgr == "systemd"
